import { createConnection } from "mysql2/promise";
import { config } from "dotenv";
config();

const conn = await createConnection(process.env.DATABASE_URL);

// ─── Seed Leads ───────────────────────────────────────────────────────────────

const leads = [
  {
    companyName: "Cognition AI",
    website: "https://cognition.ai",
    description: "Building autonomous AI software engineers. Devin, the world's first AI software engineer, runs complex coding tasks on GPU clusters for inference and code execution.",
    industry: "Artificial Intelligence",
    subIndustry: "AI Agents",
    location: "San Francisco, CA, United States",
    headcount: "11-50",
    linkedinUrl: "https://linkedin.com/company/cognition-ai",
    fundingStage: "Series B",
    totalFunding: "$175M",
    lastFundingDate: "2024-03",
    investors: "Founders Fund, Peter Thiel, Eric Schmidt",
    gpuUseCases: JSON.stringify(["inference", "training", "fine_tuning"]),
    techStack: "PyTorch, CUDA, Kubernetes, vLLM, LLaMA",
    aiProducts: "Devin AI software engineer, autonomous coding agent",
    estimatedGpuSpend: "$200K-500K/mo",
    score: 92,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 30, fundingStage: 20, industryFit: 20, headcountSignal: 12, techStackSignal: 10 }),
    pipelineStage: "New",
    recommendedGpu: "H200",
    lektraFitReason: "Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Model training/fine-tuning needs match Lektra's H200 high-memory GPU offering. Series B funding stage indicates active growth and GPU budget expansion. Lektra's 30-50% cost advantage over hyperscalers with zero egress fees provides compelling ROI.",
    source: "Manual",
  },
  {
    companyName: "Mistral AI",
    website: "https://mistral.ai",
    description: "European AI company building frontier open-weight language models. Runs massive distributed training jobs and inference infrastructure globally.",
    industry: "Generative AI",
    subIndustry: "Foundation Models",
    location: "San Francisco, CA, United States",
    headcount: "51-200",
    linkedinUrl: "https://linkedin.com/company/mistral-ai",
    fundingStage: "Series B",
    totalFunding: "$1.1B",
    lastFundingDate: "2024-06",
    investors: "a16z, Lightspeed, General Catalyst",
    gpuUseCases: JSON.stringify(["training", "inference", "fine_tuning"]),
    techStack: "PyTorch, CUDA, Triton, TensorRT, JAX",
    aiProducts: "Mistral 7B, Mixtral, Le Chat, Mistral API",
    estimatedGpuSpend: "$2M-5M/mo",
    score: 95,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 30, fundingStage: 20, industryFit: 20, headcountSignal: 15, techStackSignal: 10 }),
    pipelineStage: "Contacted",
    recommendedGpu: "H200",
    lektraFitReason: "Model training/fine-tuning needs match Lektra's H200 high-memory GPU offering. Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Series B funding stage indicates active growth. Lektra's 30-50% cost advantage provides compelling ROI for high-volume GPU spend.",
    source: "Manual",
  },
  {
    companyName: "Together AI",
    website: "https://together.ai",
    description: "Cloud platform for running and fine-tuning open-source AI models. Provides GPU compute infrastructure for AI developers at scale.",
    industry: "AI Infrastructure",
    subIndustry: "GPU Cloud",
    location: "San Francisco, CA, United States",
    headcount: "51-200",
    linkedinUrl: "https://linkedin.com/company/together-ai",
    fundingStage: "Series A",
    totalFunding: "$102M",
    lastFundingDate: "2023-11",
    investors: "Kleiner Perkins, NVIDIA, Salesforce Ventures",
    gpuUseCases: JSON.stringify(["inference", "training", "fine_tuning", "edge_compute"]),
    techStack: "CUDA, PyTorch, vLLM, Triton, Kubernetes",
    aiProducts: "Together Inference API, Together Fine-tuning, Together Training",
    estimatedGpuSpend: "$1M-3M/mo",
    score: 88,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 30, fundingStage: 18, industryFit: 20, headcountSignal: 15, techStackSignal: 5 }),
    pipelineStage: "Qualified",
    recommendedGpu: "Multiple",
    lektraFitReason: "Active AI inference workloads align with Lektra's edge GPU clusters. Edge compute requirements align with Lektra's distributed solar-powered datacenter model. Series A funding indicates active growth. Industry focus (AI Infrastructure, GPU Cloud) indicates GPU-intensive workloads.",
    source: "Manual",
  },
  {
    companyName: "Anyscale",
    website: "https://anyscale.com",
    description: "Company behind Ray, the open-source distributed computing framework. Provides managed Ray platform for scaling AI and ML workloads.",
    industry: "MLOps",
    subIndustry: "Distributed AI",
    location: "San Francisco, CA, United States",
    headcount: "51-200",
    linkedinUrl: "https://linkedin.com/company/anyscale",
    fundingStage: "Series C",
    totalFunding: "$259M",
    lastFundingDate: "2022-12",
    investors: "a16z, NEA, Google Ventures",
    gpuUseCases: JSON.stringify(["training", "inference", "fine_tuning"]),
    techStack: "Ray, PyTorch, CUDA, Kubernetes, vLLM",
    aiProducts: "Anyscale Platform, Ray Serve, RayLLM",
    estimatedGpuSpend: "$500K-1M/mo",
    score: 85,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 30, fundingStage: 20, industryFit: 20, headcountSignal: 15, techStackSignal: 0 }),
    pipelineStage: "New",
    recommendedGpu: "H200",
    lektraFitReason: "Model training/fine-tuning needs match Lektra's H200 high-memory GPU offering. Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Series C funding stage indicates active growth. Industry focus (MLOps, Distributed AI) indicates GPU-intensive workloads.",
    source: "Manual",
  },
  {
    companyName: "Runway ML",
    website: "https://runwayml.com",
    description: "AI-powered creative tools for video generation and editing. Gen-2 and Gen-3 models require massive GPU compute for video inference and rendering.",
    industry: "Generative AI",
    subIndustry: "Video AI",
    location: "New York, NY, United States",
    headcount: "51-200",
    linkedinUrl: "https://linkedin.com/company/runwayml",
    fundingStage: "Series C",
    totalFunding: "$237M",
    lastFundingDate: "2023-06",
    investors: "Google, Salesforce, NVIDIA",
    gpuUseCases: JSON.stringify(["inference", "training", "remote_viz"]),
    techStack: "PyTorch, CUDA, Diffusion Models, TensorRT",
    aiProducts: "Gen-2 video generation, Gen-3 Alpha, AI Magic Tools",
    estimatedGpuSpend: "$1M-2M/mo",
    score: 87,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 30, fundingStage: 20, industryFit: 20, headcountSignal: 15, techStackSignal: 2 }),
    pipelineStage: "New",
    recommendedGpu: "RTX Pro 6000",
    lektraFitReason: "Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Remote visualization use case is a direct fit for Lektra's RTX Pro 6000 nodes. Series C funding stage indicates active growth. Lektra's 30-50% cost advantage provides compelling ROI.",
    source: "Manual",
  },
  {
    companyName: "Perplexity AI",
    website: "https://perplexity.ai",
    description: "AI-powered answer engine and search platform. Runs large language model inference at massive scale to power real-time search queries.",
    industry: "Artificial Intelligence",
    subIndustry: "AI Search",
    location: "San Francisco, CA, United States",
    headcount: "51-200",
    linkedinUrl: "https://linkedin.com/company/perplexity-ai",
    fundingStage: "Series B",
    totalFunding: "$520M",
    lastFundingDate: "2024-04",
    investors: "IVP, NEA, Jeff Bezos",
    gpuUseCases: JSON.stringify(["inference", "fine_tuning"]),
    techStack: "vLLM, PyTorch, CUDA, Triton, TensorRT",
    aiProducts: "Perplexity Answer Engine, Perplexity Pro, Sonar API",
    estimatedGpuSpend: "$3M-8M/mo",
    score: 90,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 28, fundingStage: 20, industryFit: 20, headcountSignal: 15, techStackSignal: 7 }),
    pipelineStage: "Contacted",
    recommendedGpu: "H200",
    lektraFitReason: "Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Series B funding stage indicates active growth and GPU budget expansion. Industry focus (AI Search) indicates GPU-intensive inference workloads. Lektra's zero egress fees are particularly valuable for high-query-volume inference.",
    source: "Manual",
  },
  {
    companyName: "Modal Labs",
    website: "https://modal.com",
    description: "Cloud platform for running AI and ML code at scale. Provides serverless GPU infrastructure for AI developers with instant cold starts.",
    industry: "AI Infrastructure",
    subIndustry: "Serverless GPU",
    location: "New York, NY, United States",
    headcount: "11-50",
    linkedinUrl: "https://linkedin.com/company/modal-labs",
    fundingStage: "Series A",
    totalFunding: "$16M",
    lastFundingDate: "2023-02",
    investors: "Redpoint Ventures, Madrona",
    gpuUseCases: JSON.stringify(["inference", "training", "fine_tuning", "edge_compute"]),
    techStack: "CUDA, PyTorch, Kubernetes, gVisor",
    aiProducts: "Modal Serverless GPU platform, Modal Functions",
    estimatedGpuSpend: "$200K-500K/mo",
    score: 82,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 30, fundingStage: 18, industryFit: 20, headcountSignal: 12, techStackSignal: 2 }),
    pipelineStage: "New",
    recommendedGpu: "Multiple",
    lektraFitReason: "Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Edge compute requirements align with Lektra's distributed solar-powered datacenter model. Series A funding indicates active growth. Lektra's 30-50% cost advantage is compelling for a cost-sensitive infrastructure startup.",
    source: "Manual",
  },
  {
    companyName: "Weights & Biases",
    website: "https://wandb.ai",
    description: "MLOps platform for tracking, visualizing, and optimizing machine learning experiments. Customers run large GPU training jobs tracked through W&B.",
    industry: "MLOps",
    subIndustry: "ML Experiment Tracking",
    location: "San Francisco, CA, United States",
    headcount: "201-500",
    linkedinUrl: "https://linkedin.com/company/weights-biases",
    fundingStage: "Series C",
    totalFunding: "$200M",
    lastFundingDate: "2021-10",
    investors: "Coatue, Insight Partners, NEA",
    gpuUseCases: JSON.stringify(["training", "fine_tuning"]),
    techStack: "PyTorch, TensorFlow, CUDA, Kubernetes, Spark",
    aiProducts: "W&B Experiments, W&B Sweeps, W&B Artifacts, W&B Launch",
    estimatedGpuSpend: "$300K-800K/mo",
    score: 78,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 28, fundingStage: 20, industryFit: 20, headcountSignal: 10, techStackSignal: 0 }),
    pipelineStage: "New",
    recommendedGpu: "H200",
    lektraFitReason: "Model training/fine-tuning needs match Lektra's H200 high-memory GPU offering. Series C funding stage indicates active growth. Industry focus (MLOps) indicates GPU-intensive workloads. Lektra's 30-50% cost advantage provides compelling ROI.",
    source: "Manual",
  },
  {
    companyName: "Cohere",
    website: "https://cohere.com",
    description: "Enterprise AI platform providing large language models for business applications. Runs massive inference and fine-tuning workloads for enterprise customers.",
    industry: "Generative AI",
    subIndustry: "Enterprise LLM",
    location: "San Francisco, CA, United States",
    headcount: "201-500",
    linkedinUrl: "https://linkedin.com/company/cohere-ai",
    fundingStage: "Series C",
    totalFunding: "$445M",
    lastFundingDate: "2023-06",
    investors: "Tiger Global, Salesforce, NVIDIA",
    gpuUseCases: JSON.stringify(["inference", "training", "fine_tuning"]),
    techStack: "JAX, PyTorch, CUDA, Triton, TensorRT",
    aiProducts: "Command R, Embed, Rerank, Coral enterprise platform",
    estimatedGpuSpend: "$2M-5M/mo",
    score: 88,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 30, fundingStage: 20, industryFit: 20, headcountSignal: 13, techStackSignal: 5 }),
    pipelineStage: "Contacted",
    recommendedGpu: "H200",
    lektraFitReason: "Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Model training/fine-tuning needs match Lektra's H200 high-memory GPU offering. Series C funding stage indicates active growth. Lektra's zero egress fees are particularly valuable for high-volume enterprise inference.",
    source: "Manual",
  },
  {
    companyName: "Stability AI",
    website: "https://stability.ai",
    description: "Open-source AI company behind Stable Diffusion image generation models. Runs large-scale GPU training and inference for image, video, and audio generation.",
    industry: "Generative AI",
    subIndustry: "Image Generation",
    location: "San Francisco, CA, United States",
    headcount: "51-200",
    linkedinUrl: "https://linkedin.com/company/stability-ai",
    fundingStage: "Series A",
    totalFunding: "$101M",
    lastFundingDate: "2022-10",
    investors: "Coatue, Lightspeed, O'Shaughnessy Ventures",
    gpuUseCases: JSON.stringify(["training", "inference", "remote_viz"]),
    techStack: "PyTorch, CUDA, Diffusion Models, ONNX",
    aiProducts: "Stable Diffusion, SDXL, Stable Video Diffusion, Stable Audio",
    estimatedGpuSpend: "$500K-2M/mo",
    score: 80,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 30, fundingStage: 18, industryFit: 20, headcountSignal: 12, techStackSignal: 0 }),
    pipelineStage: "New",
    recommendedGpu: "RTX Pro 6000",
    lektraFitReason: "Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Remote visualization use case is a direct fit for Lektra's RTX Pro 6000 nodes. Series A funding indicates active growth. Lektra's 30-50% cost advantage is compelling for a cost-sensitive AI startup.",
    source: "Manual",
  },
  {
    companyName: "Replicate",
    website: "https://replicate.com",
    description: "Cloud platform for running machine learning models via API. Hosts thousands of open-source models on GPU infrastructure for developers.",
    industry: "AI Infrastructure",
    subIndustry: "Model Hosting",
    location: "San Francisco, CA, United States",
    headcount: "11-50",
    linkedinUrl: "https://linkedin.com/company/replicate",
    fundingStage: "Series B",
    totalFunding: "$40M",
    lastFundingDate: "2023-08",
    investors: "Andreessen Horowitz, Y Combinator",
    gpuUseCases: JSON.stringify(["inference", "fine_tuning", "edge_compute"]),
    techStack: "CUDA, PyTorch, Docker, Kubernetes, ONNX",
    aiProducts: "Replicate API, Cog model packaging, Deployments",
    estimatedGpuSpend: "$300K-800K/mo",
    score: 83,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 30, fundingStage: 20, industryFit: 20, headcountSignal: 12, techStackSignal: 1 }),
    pipelineStage: "New",
    recommendedGpu: "RTX Pro 6000",
    lektraFitReason: "Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Edge compute requirements align with Lektra's distributed solar-powered datacenter model. Series B funding indicates active growth. Lektra's 30-50% cost advantage is compelling for a developer-focused GPU platform.",
    source: "Manual",
  },
  {
    companyName: "Fireworks AI",
    website: "https://fireworks.ai",
    description: "Fast inference platform for open-source AI models. Provides the fastest LLM inference API with GPU optimization for production AI applications.",
    industry: "AI Infrastructure",
    subIndustry: "LLM Inference",
    location: "San Francisco, CA, United States",
    headcount: "11-50",
    linkedinUrl: "https://linkedin.com/company/fireworks-ai",
    fundingStage: "Series A",
    totalFunding: "$52M",
    lastFundingDate: "2024-01",
    investors: "Benchmark, Sequoia",
    gpuUseCases: JSON.stringify(["inference", "fine_tuning"]),
    techStack: "vLLM, CUDA, TensorRT, PyTorch, Triton",
    aiProducts: "Fireworks Inference API, FireFunction, FireLLaVA",
    estimatedGpuSpend: "$200K-600K/mo",
    score: 84,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 28, fundingStage: 18, industryFit: 20, headcountSignal: 12, techStackSignal: 6 }),
    pipelineStage: "Qualified",
    recommendedGpu: "H200",
    lektraFitReason: "Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Series A funding indicates active growth. Industry focus (LLM Inference) indicates GPU-intensive workloads. Lektra's zero egress fees are particularly valuable for high-volume inference APIs.",
    source: "Manual",
  },
  {
    companyName: "Lepton AI",
    website: "https://lepton.ai",
    description: "AI cloud platform for running and deploying LLMs and AI applications. Provides GPU compute with a developer-friendly API for AI startups.",
    industry: "AI Infrastructure",
    subIndustry: "AI Cloud",
    location: "San Jose, CA, United States",
    headcount: "11-50",
    linkedinUrl: "https://linkedin.com/company/lepton-ai",
    fundingStage: "Seed",
    totalFunding: "$27M",
    lastFundingDate: "2023-07",
    investors: "Lightspeed, GGV Capital",
    gpuUseCases: JSON.stringify(["inference", "training", "edge_compute"]),
    techStack: "PyTorch, CUDA, Kubernetes, vLLM",
    aiProducts: "Lepton AI Platform, LLM inference, Photon deployment",
    estimatedGpuSpend: "$100K-300K/mo",
    score: 76,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 30, fundingStage: 14, industryFit: 20, headcountSignal: 12, techStackSignal: 0 }),
    pipelineStage: "New",
    recommendedGpu: "RTX Pro 6000",
    lektraFitReason: "Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Edge compute requirements align with Lektra's distributed solar-powered datacenter model. Seed funding stage indicates early growth. Lektra's 30-50% cost advantage is particularly compelling for a cost-sensitive early-stage startup.",
    source: "Manual",
  },
  {
    companyName: "Baseten",
    website: "https://baseten.co",
    description: "ML model deployment platform for production AI applications. Enables teams to deploy and serve ML models with GPU-optimized infrastructure.",
    industry: "MLOps",
    subIndustry: "Model Deployment",
    location: "San Francisco, CA, United States",
    headcount: "11-50",
    linkedinUrl: "https://linkedin.com/company/baseten",
    fundingStage: "Series B",
    totalFunding: "$40M",
    lastFundingDate: "2023-03",
    investors: "Spark Capital, Greylock",
    gpuUseCases: JSON.stringify(["inference", "fine_tuning"]),
    techStack: "PyTorch, CUDA, Triton, TensorRT, Kubernetes",
    aiProducts: "Baseten deployment platform, Truss model packaging",
    estimatedGpuSpend: "$150K-400K/mo",
    score: 79,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 28, fundingStage: 20, industryFit: 20, headcountSignal: 12, techStackSignal: -1 }),
    pipelineStage: "New",
    recommendedGpu: "RTX Pro 6000",
    lektraFitReason: "Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Series B funding indicates active growth. Industry focus (MLOps, Model Deployment) indicates GPU-intensive workloads. Lektra's 30-50% cost advantage provides compelling ROI.",
    source: "Manual",
  },
  {
    companyName: "OctoAI",
    website: "https://octo.ai",
    description: "AI compute platform for running generative AI models at scale. Provides optimized GPU inference for image, text, and code generation models.",
    industry: "AI Infrastructure",
    subIndustry: "Generative AI Compute",
    location: "Seattle, WA, United States",
    headcount: "11-50",
    linkedinUrl: "https://linkedin.com/company/octoai",
    fundingStage: "Series B",
    totalFunding: "$132M",
    lastFundingDate: "2023-05",
    investors: "Madrona, Tiger Global, NVIDIA",
    gpuUseCases: JSON.stringify(["inference", "fine_tuning", "remote_viz"]),
    techStack: "CUDA, TensorRT, PyTorch, ONNX, Triton",
    aiProducts: "OctoAI Compute Service, Image Gen API, Text Gen API",
    estimatedGpuSpend: "$300K-800K/mo",
    score: 82,
    scoreBreakdown: JSON.stringify({ gpuUseCases: 30, fundingStage: 20, industryFit: 20, headcountSignal: 12, techStackSignal: 0 }),
    pipelineStage: "Contacted",
    recommendedGpu: "RTX Pro 6000",
    lektraFitReason: "Active AI inference workloads align with Lektra's low-latency edge GPU clusters. Remote visualization use case is a direct fit for Lektra's RTX Pro 6000 nodes. Series B funding indicates active growth. Lektra's 30-50% cost advantage provides compelling ROI.",
    source: "Manual",
  },
];

// Insert leads
for (const lead of leads) {
  await conn.execute(
    `INSERT INTO leads (companyName, website, description, industry, subIndustry, location, headcount, linkedinUrl, fundingStage, totalFunding, lastFundingDate, investors, gpuUseCases, techStack, aiProducts, estimatedGpuSpend, score, scoreBreakdown, pipelineStage, recommendedGpu, lektraFitReason, source)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      lead.companyName, lead.website, lead.description, lead.industry, lead.subIndustry,
      lead.location, lead.headcount, lead.linkedinUrl, lead.fundingStage, lead.totalFunding,
      lead.lastFundingDate, lead.investors, lead.gpuUseCases, lead.techStack, lead.aiProducts,
      lead.estimatedGpuSpend, lead.score, lead.scoreBreakdown, lead.pipelineStage,
      lead.recommendedGpu, lead.lektraFitReason, lead.source,
    ]
  );
}

// Get inserted lead IDs
const [rows] = await conn.execute("SELECT id, companyName FROM leads ORDER BY id DESC LIMIT 15");
const leadMap = {};
for (const row of rows) {
  leadMap[row.companyName] = row.id;
}

// ─── Seed Contacts ────────────────────────────────────────────────────────────

const contacts = [
  {
    company: "Cognition AI",
    firstName: "Scott", lastName: "Wu", title: "CEO & Co-Founder",
    linkedinUrl: "https://linkedin.com/in/scott-wu-cognition",
    isPrimary: true,
    fitReason: "CEO and technical co-founder driving all infrastructure decisions. Former competitive programmer with deep ML background. Direct decision-maker for GPU compute spend.",
  },
  {
    company: "Mistral AI",
    firstName: "Arthur", lastName: "Mensch", title: "CEO & Co-Founder",
    linkedinUrl: "https://linkedin.com/in/arthur-mensch",
    isPrimary: true,
    fitReason: "CEO and co-founder. Former DeepMind researcher. Drives all major infrastructure and compute decisions for Mistral's training and inference stack.",
  },
  {
    company: "Together AI",
    firstName: "Vipul", lastName: "Ved Prakash", title: "CEO & Co-Founder",
    linkedinUrl: "https://linkedin.com/in/vipulvedprakash",
    isPrimary: true,
    fitReason: "CEO with deep background in distributed systems and AI infrastructure. Directly oversees GPU compute partnerships and infrastructure strategy.",
  },
  {
    company: "Anyscale",
    firstName: "Robert", lastName: "Nishihara", title: "CEO & Co-Founder",
    linkedinUrl: "https://linkedin.com/in/robert-nishihara",
    isPrimary: true,
    fitReason: "CEO and co-creator of Ray framework. UC Berkeley PhD in ML. Drives all infrastructure and compute decisions for Anyscale's distributed GPU platform.",
  },
  {
    company: "Runway ML",
    firstName: "Cristóbal", lastName: "Valenzuela", title: "CEO & Co-Founder",
    linkedinUrl: "https://linkedin.com/in/cvalenzuelab",
    isPrimary: true,
    fitReason: "CEO driving Runway's video AI infrastructure. Oversees massive GPU compute requirements for Gen-2/Gen-3 video generation models.",
  },
  {
    company: "Perplexity AI",
    firstName: "Aravind", lastName: "Srinivas", title: "CEO & Co-Founder",
    linkedinUrl: "https://linkedin.com/in/aravind-srinivas-16051987",
    isPrimary: true,
    fitReason: "CEO with OpenAI and DeepMind background. Drives all infrastructure decisions for Perplexity's massive LLM inference stack. Key decision-maker for GPU compute partnerships.",
  },
  {
    company: "Modal Labs",
    firstName: "Erik", lastName: "Bernhardsson", title: "CEO & Co-Founder",
    linkedinUrl: "https://linkedin.com/in/erikbern",
    isPrimary: true,
    fitReason: "CEO and former Spotify ML lead. Deep infrastructure expertise. Drives all GPU compute decisions for Modal's serverless GPU platform.",
  },
  {
    company: "Fireworks AI",
    firstName: "Lin", lastName: "Qiao", title: "CEO & Co-Founder",
    linkedinUrl: "https://linkedin.com/in/lin-qiao-fireworks",
    isPrimary: true,
    fitReason: "CEO and former Facebook AI infrastructure lead. Deep expertise in GPU optimization and inference. Key decision-maker for Fireworks' GPU compute partnerships.",
  },
  {
    company: "Replicate",
    firstName: "Ben", lastName: "Firshman", title: "CEO & Co-Founder",
    linkedinUrl: "https://linkedin.com/in/bfirsh",
    isPrimary: true,
    fitReason: "CEO and Docker co-creator. Deep infrastructure background. Drives all GPU compute and infrastructure decisions for Replicate's model hosting platform.",
  },
  {
    company: "Cohere",
    firstName: "Aidan", lastName: "Gomez", title: "CEO & Co-Founder",
    linkedinUrl: "https://linkedin.com/in/aidangomez",
    isPrimary: true,
    fitReason: "CEO and Transformer paper co-author. Drives all infrastructure decisions for Cohere's enterprise LLM platform. Key decision-maker for GPU compute partnerships.",
  },
];

for (const contact of contacts) {
  const leadId = leadMap[contact.company];
  if (!leadId) continue;
  await conn.execute(
    `INSERT INTO contacts (leadId, firstName, lastName, title, linkedinUrl, isPrimary, fitReason)
     VALUES (?, ?, ?, ?, ?, ?, ?)`,
    [leadId, contact.firstName, contact.lastName, contact.title, contact.linkedinUrl, contact.isPrimary ? 1 : 0, contact.fitReason]
  );
}

await conn.end();
console.log(`✅ Seeded ${leads.length} leads and ${contacts.length} contacts`);
